name: example
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^5.5.0+1
  native_updater:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
